<div>
    <h3><?php echo $this->__('Popular Countries')?></h3>
    <ul>
		<?php foreach ($countries as $country): ?>
            <li>
                <a href="<?php echo $this->escapeHtmlAttr($this->r('search', [], ['field' => 'country', 'q' => $country['country']])) ?>">
					<?php echo $this->e($country['country']) ?>
                </a>
            </li>
		<?php endforeach; ?>
    </ul>
</div>
