<div>
    <h3><?php echo $this->__('Popular Languages')?></h3>
    <ul>
		<?php foreach ($languages as $language): ?>
            <li>
                <a href="<?php echo $this->escapeHtmlAttr($this->r('search', [], ['field' => 'language', 'q' => $language['language']])) ?>">
					<?php echo $this->e(Friendica\Directory\Utils\L10n::localeToLanguageString($language['language'])) ?>
                </a>
            </li>
		<?php endforeach; ?>
    </ul>
</div>
