<div class="row">
    <div class="col-xl-9 col-lg-8">
		<?php echo $this->fetch('sub/profiles.phtml', [
			'page' => 'directory',
			'profiles' => $profiles,
			'accountTypeTabs' => $accountTypeTabs,
			'pager_full' => $pager_full,
			'pager_minimal' => $pager_minimal
		]) ?>
    </div>
    <div class="col-xl-3 col-lg-4">
		<?php echo $popularTags ?>
		<?php echo $popularCountries ?>
		<?php echo $popularLanguages ?>
    </div>
</div>

