<!DOCTYPE html>
<html lang="<?php echo $lang?>">
<head>
    <title><?php echo $this->__('Friendica Directory')?></title>
    <base href="<?php echo $baseUrl ?>">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="assets/css/friendica-directory.min.css">
    <link rel="stylesheet" href="assets/vendor/fontawesome/web-fonts-with-css/css/solid.css">
    <link rel="stylesheet" href="assets/vendor/fontawesome/web-fonts-with-css/css/fontawesome.css">
</head>
<body>
<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-light bg-light static-top">
    <div class="container">
        <a class="navbar-brand" href="">
            <img src="assets/images/friendica-32.png" width="32" height="32" class="d-inline-block align-top" alt="">
	        <?php echo $this->__('Friendica Directory')?>
        </a>
		<?php if (empty($noNavSearch)): ?>
            <form class="form-inline my-2 my-lg-0 d-none d-md-flex" action="search">
                <div class="input-group">
                    <label class="sr-only" for="header_search"><?php echo $this->__('Search terms')?></label>
                    <input name="q" class="form-control" type="search" id="header_search" placeholder="<?php echo $this->p__('noun', 'Search')?>..."
                           aria-label="<?php echo $this->__('Search terms')?>">
                    <div class="input-group-append">
                        <button class="btn btn-primary" type="submit"><?php echo $this->p__('verb', 'Search')?></button>
                    </div>
                </div>
            </form>
		<?php endif; ?>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="<?php echo $this->__('Toggle navigation')?>">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse pt-2" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
				<?php if (empty($noNavSearch)): ?>
                    <li class="nav-item d-md-none">
                        <form action="search">
                            <div class="input-group">
                                <label class="sr-only" for="nav_search"><?php echo $this->__('Search terms')?></label>
                                <input name="q" class="form-control form-control-sm" type="search" id="nav_search"
                                       placeholder="<?php echo $this->p__('noun', 'Search')?>..." aria-label="<?php echo $this->__('Search terms')?>">
                                <div class="input-group-append">
                                    <button class="btn btn-primary btn-sm" type="submit"><?php echo $this->p__('verb', 'Search')?></button>
                                </div>
                            </div>
                        </form>
                    </li>
				<?php endif; ?>

                <li class="nav-item">
                    <a class="nav-link" href=""><i class="fa fa-address-card"></i> <?php echo $this->__('Directory')?>
                        <!--<span class="sr-only">(current)</span>-->
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="servers"><i class="fa fa-hotel"></i> <?php echo $this->__('Public servers')?></a>
                </li>
                <li class="nav-item">
                    <div class="dropdown">
                        <button class="btn btn-link nav-link dropdown-toggle" type="button" id="languageDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fa fa-language"></i> <?php echo $this->__('Language')?>
                        </button>
                        <div class="dropdown-menu" aria-labelledby="languageDropdown">
                    <?php foreach($languages as $lang):?>
                            <a class="dropdown-item" href="?lang=<?php echo $this->escapeUrl($lang)?>">
	                            <?php echo $this->e(Friendica\Directory\Utils\L10n::localeToLanguageString($lang)) ?>
                            </a>
                    <?php endforeach;?>
                        </div>
                    </div>
                </li>
            </ul>
            
        </div>
    </div>
</nav>

<!-- Page Content -->
<div class="container pt-3">
	<?php echo $content ?>
</div>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <ul class="navbar-nav">
            <li class="nav-item">
                <span class="nav-link disabled"><?php echo $this->__('Friendica Directory version %s', $version)?></span>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="https://github.com/friendica/friendica-directory"><?php echo $this->__('Source Code on GitHub')?> <i class="fa fa-external-link-alt"></i></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="stats"><i class="fa fa-clipboard-list"></i> <?php echo $this->__('Stats')?></a>
            </li>
        </ul>
    </div>
</nav>
<script type="text/javascript" src="assets/vendor/bootstrap.native/dist/bootstrap-native-v4.min.js"></script>
</body>
</html>

