<!--<h1>Search</h1>-->
<form action="search">
    <div class="input-group">
        <label class="sr-only" for="search_search">Search terms</label>
        <input name="q" class="form-control" type="search" id="search_search" placeholder="Search..."
               aria-label="Search terms" value="<?php echo $this->escapeHtmlAttr($query) ?>">
        <div class="input-group-append">
            <button class="btn btn-primary" type="submit">Search</button>
        </div>
    </div>
</form>

<h2><?php echo $count ?> results for "<?php echo $this->e($query) ?>"</h2>
<?php echo $this->fetch('sub/profiles.phtml', [
	'page' => 'search',
	'profiles' => $profiles,
	'accountTypeTabs' => $accountTypeTabs,
	'pager_full' => $pager_full,
	'pager_minimal' => $pager_minimal
]) ?>
