<h1><?php echo $this->e($title) ?> (<?php echo $this->e($total)?>)</h1>
<?php if ($language):?>
	<p><?php echo $this->__('Filtered by language:')?> <span class="badge badge-secondary"><?php echo $this->e(\Friendica\Directory\Utils\L10n::localeToLanguageString($language)) ?></span> <a href="<?php echo $this->r('servers')?>"><?php echo $this->__('Clear language filter')?></a></p>
<?php else:?>
<?php echo $popularLanguages?>
<?php endif;?>
<nav aria-label="<?php echo $this->__('Top servers pagination')?>">
	<?php echo $this->fetch('sub/pager_full.phtml', $pager) ?>
</nav>
<div class="row">
	<?php foreach ($servers as $server) : ?>
        <div class="col-xl-6">
			<?php echo $this->fetch('sub/server.phtml', ['server' => $server, 'stable_version' => $stable_version, 'rc_version' => $rc_version, 'dev_version' => $dev_version]) ?>
        </div>
	<?php endforeach; ?>
</div>
<nav aria-label="<?php echo $this->__('Bottom servers pagination')?>">
	<?php echo $this->fetch('sub/pager_full.phtml', $pager) ?>
</nav>
