<?php
use \Friendica\Directory\Utils\L10n;
?>
<h1><?php echo $this->__('Directory statistics') ?></h1>
<h2><?php echo $this->__('Profiles') ?></h2>
<p><?php echo $this->__('This directory knows about <strong>%s distinct potential profile URLs</strong>.', L10n::formatNumber($stats['profile_queue']['total']))?></p>
<p><?php echo $this->__('Out of those, there are <strong>%s profiles (%s)</strong> that opted in the public directory at least once.',
        L10n::formatNumber($stats['profile']['total']),
        L10n::formatNumber($stats['profile']['ratio'], L10n::PERCENT)
    )?></p>
<p><?php echo $this->__('Out of those, there currently are <strong>%s available profiles (%s)</strong>. <a href="/">Check them out!</a>',
		L10n::formatNumber($stats['profile']['available']['total']),
        L10n::formatNumber($stats['profile']['available']['ratio'], L10n::PERCENT)
    )?></p>
<h3><?php echo $this->__('Languages') ?></h3>
<p><?php echo $this->__('Out of <strong>%s</strong> profiles reporting their language there are:', L10n::formatNumber($stats['profile']['language']['total']))?></p>
<ul>
    <?php foreach($stats['profile']['languages'] as $language):?>
    <li>
        <strong><?php echo L10n::formatNumber($language['total'])?></strong>
        <?php echo empty($language['language']) ? 'N/A' : L10n::localeToLanguageString($language['language'])?>
        (<?php echo L10n::formatNumber($language['ratio'], L10n::PERCENT)?>)
    </li>
    <?php endforeach;?>
</ul>
<h2><?php echo $this->__('Servers') ?></h2>
<p><?php echo $this->__('This directory knows about <strong>%s distinct potential server URLs</strong>.', L10n::formatNumber($stats['server_queue']['total']))?></p>
<p><?php echo $this->__('Out of those, there are <strong>%s domains (%s)</strong> that have been a Friendica server at least once.',
		L10n::formatNumber($stats['server']['total']),
		L10n::formatNumber($stats['server']['ratio'], L10n::PERCENT))
	?></p>
<p><?php echo $this->__('Out of those, there are:')?></p>
<ul>
    <li><?php echo $this->__('<strong>%s available servers (%s)</strong>',
        L10n::formatNumber($stats['server']['available']['total']),
        L10n::formatNumber($stats['server']['available']['ratio'], L10n::PERCENT)
    )?></li>
    <li><?php echo $this->__('<strong>%s public servers (%s)</strong> currently open for registration. <a href="/servers">Check them out!</a>',
        L10n::formatNumber($stats['server']['open']['total']),
        L10n::formatNumber($stats['server']['open']['ratio'], L10n::PERCENT)
    )?></li>
</ul>

<h3><?php echo $this->__('Languages') ?></h3>
<p><?php echo $this->__('Out of <strong>%s</strong> servers reporting their language there are:', L10n::formatNumber($stats['server']['language']['total']))?></p>
<ul>
	<?php foreach($stats['server']['languages'] as $language):?>
        <li>
            <strong><?php echo L10n::formatNumber($language['total'])?></strong>
			<?php echo L10n::localeToLanguageString($language['language'])?>
            (<?php echo L10n::formatNumber($language['ratio'], L10n::PERCENT)?>)
        </li>
	<?php endforeach;?>
</ul>
<h3><?php echo $this->__('Versions') ?></h3>
<p><?php echo $this->__('Out of <strong>%s</strong> servers reporting their version there are:', L10n::formatNumber($stats['server']['version']['total']))?></p>
<ul>
	<?php foreach($stats['server']['versions'] as $version):?>
        <li>
            <strong><?php echo L10n::formatNumber($version['total'])?></strong>
            <code><?php echo $this->e($version['version'])?></code>
            (<?php echo L10n::formatNumber($version['ratio'], L10n::PERCENT)?>)
            <?php if ($version['version'] == $stable_version):?>
            <span class="badge badge-success"><i class="fa fa-smile"></i> <?php echo $this->__('Stable Version')?></span>
            <?php elseif ($version['version'] == $dev_version):?>
            <span class="badge badge-secondary"><i class="fa fa-poo"></i> <?php echo $this->__('Develop Version')?></span>
            <?php endif;?>
        </li>
	<?php endforeach;?>
</ul>