<?php if (!empty($prev) || !empty($next)): ?>
    <ul class="pagination justify-content-center">
		<?php if (!empty($first)): ?>
            <li class="page-item <?php echo $first['class'] ?>">
                <a class="page-link" href="<?php echo $first['url'] ?>" tabindex="-1">
                    <span aria-hidden="true">&laquo;</span>
					<?php echo $first['text'] ?>
                </a>
            </li>
		<?php endif; ?>
		<?php if (!empty($prev)): ?>
            <li class="page-item <?php echo $prev['class'] ?>">
                <a class="page-link" href="<?php echo $prev['url'] ?>" tabindex="-1">
                    <span aria-hidden="true">&lsaquo;</span>
					<?php echo $prev['text'] ?>
                </a>
            </li>
		<?php endif; ?>
		<?php foreach ($pages as $page): ?>
            <li class="page-item <?php echo $page['class'] ?>">
                <a class="page-link" href="<?php echo $page['url'] ?>" tabindex="-1"><?php echo $page['text'] ?></a>
            </li>
		<?php endforeach; ?>
		<?php if (!empty($next)): ?>
            <li class="page-item <?php echo $next['class'] ?>">
                <a class="page-link" href="<?php echo $next['url'] ?>" tabindex="-1">
					<?php echo $next['text'] ?>
                    <span aria-hidden="true">&rsaquo;</span>
                </a>
            </li>
		<?php endif; ?>
		<?php if (!empty($last)): ?>
            <li class="page-item <?php echo $last['class'] ?>">
                <a class="page-link" href="<?php echo $last['url'] ?>" tabindex="-1">
					<?php echo $last['text'] ?>
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
		<?php endif; ?>
    </ul>
<?php endif; ?>
