<nav aria-label="<?php echo $this->__('Account type tabs')?>" class="mb-3">
	<?php echo $accountTypeTabs ?>
</nav>
<nav aria-label="<?php echo $this->__('Top %s pagination', $page)?>" class="d-none d-md-block">
	<?php echo $this->fetch('sub/pager_full.phtml', $pager_full) ?>
</nav>
<nav aria-label="<?php echo $this->__('Top %s pagination', $page)?>" class="d-md-none">
	<?php echo $this->fetch('sub/pager_minimal.phtml', $pager_minimal) ?>
</nav>
<?php foreach ($profiles as $profile) : ?>
	<?php echo $this->fetch('sub/profile.phtml', ['profile' => $profile]) ?>
<?php endforeach; ?>
<nav aria-label="<?php echo $this->__('Bottom %s pagination', $page)?>" class="d-none d-md-block">
	<?php echo $this->fetch('sub/pager_full.phtml', $pager_full) ?>
</nav>
<nav aria-label="<?php echo $this->__('Bottom %s pagination', $page)?>" class="d-md-none">
	<?php echo $this->fetch('sub/pager_minimal.phtml', $pager_minimal) ?>
</nav>
